# ~/.config/starship.toml

[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡ï¸"
discharging_symbol = "ğŸ’€"

[[battery.display]]
threshold = 15
style = "bold red"

[[battery.display]]
threshold = 40
style = "bold yellow"

[[battery.display]]
threshold = 100
style = "bold green"

[character]
success_symbol = "[â¯](bold yellow)"
error_symbol = "[âœ—](bold red)"

[directory]
truncate_to_repo = false

[git_status]
format = '([$all_status$ahead_behind]($style) )'
ahead = "[â‡¡${count}](bold purple)"
diverged = "[â‡¡${ahead_count}â‡£${behind_count}](bold purple)"
behind = "[â‡£${count}](bold purple)"
untracked = "[?${count}](bold yellow)"
stashed = "[S](bold green)"
modified = "[!${count}](bold yellow)"
staged = "[+${count}](bold green)"
renamed = "[r${count}](bold yellow)"
deleted = "[âœ˜${count}](bold red)"

[time]
disabled = false
format = "[ğŸ•™$time](bold cyan)"
